import { MODULE_NAME } from './constants';
export const CHANGE_DEFAULT_PANCAKE_TYPE = `${MODULE_NAME}.CHANGE_DEFAULT_PANCAKE_TYPE`;
export const ADD_TO_TOWER = `${MODULE_NAME}.ADD_TO_TOWER`;
export const REMOVE_FROM_TOWER = `${MODULE_NAME}.REMOVE_FROM_TOWER`;
export const RESET_PANCAKE = `${MODULE_NAME}.RESET_PANCAKE`;
